---
- name: Crear nueva instancia
  os_server:
       state: present
       name: "{{ instance_name }}"
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
       meta:
        hostname: webserver
  register: infra
- debug:
    var: infra

- name: Agrega instancia a inventario
  add_host:
    name: "{{ infra.server.name }}" 
    groups: webservers
    ansible_ssh_host: "{{ infra.server.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"





