---
- name: Crear nueva instancia
  os_server:
       state: present
       name: "{{ instance_name }}"
       key_name: "{{ key_name }}"
       image: "{{ image }}"
       flavor: "{{ flavor }}"
       network: "{{ network }}"
  register: infra
- debug:
    var: infra
