- name: crear keys 
  os_keypair:
    state: present
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      project_id: "{{ project_id }}"
      user_domain_name: "{{ user_domain_name }}"
    name: "{{ key_name }}"
    public_key_file:  "/home/frodriguez/.ssh/id_rsa.pub"
  register: key  