---
 
- name: install mariadb-server
  yum: name={{ item }} state=present
  with_items:
  - mariadb
  - mariadb-server
  - MySQL-python
  - mysql-connector-python

- name: Start Mysql Service
  service: 
    name: mariadb 
    state: started 
    enabled: yes



- name: Check root pass
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mysql.root_pass }}"
    host: localhost
    login_unix_socket: "{{ mysql_sock }}"
    state: present
  when: root_pwd_check.rc == 0

- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mysql.root_pass }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mysql.root_pass  }}"
    login_unix_socket: "{{ mysql_sock }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0




- name: flush privileges
  command: 'mysql -ne "{{ item }}" -uroot -p"{{  mysql.root_pass }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
 
- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    login_user: root
    login_password: "{{ mysql.root_pass }}"
    state: absent
 
- name: Create cop database and access to it
  mysql_db:
    name: "{{ mysql.db }}"
    login_user: root
    login_password: "{{  mysql.root_pass }}"
    state: present
 
- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}" -uroot -p"{{  mysql.root_pass }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
 
- name: flush privileges
  command: 'mysql -ne "{{ item }}" -uroot -p"{{  mysql.root_pass }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False




