---
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index test page
  template:
    src: "files/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"

- name: Set up Apache virtuahHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/httpd/{{ http_conf }}"

- name: Enable new site
  shell: /etc/httpd/conf.d/felix.com {{ http_conf }}
  notify: Reload Apache



- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

