---
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index test page
  template:
    src: "files/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"
    mode: '0755'

- name: Set up Apache virtuahHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"

- name: start apache
  service: 
    name: httpd
    state: started





